CFIProject/CFIProject/Models/Add.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CFIProject.Models
{
    
    public class Add : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CFIProject/CFIProject/Models/ErrorViewModel.cs
using System;

namespace CFIProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CFIProject/CFIProject/Models/NationalModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CFIProject.Models
{
    public class National
    {
        public decimal ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Website { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Assistance { get; set; }
        public int NationalID { get; set; }
    }
}

CFIProject/CFIProject/Models/OhioModels.cs
namespace CFIProject.Models
{
    public class OhioModels
    {
        public decimal ohio_ID { get; set; }
        public string ohio_Name { get; set; }
        public string ohio_Address { get; set; }
        public string ohio_Website { get; set; }
        public string ohio_Phone { get; set; }
        public string ohio_Email { get; set; }
        public string ohio_Assistance { get; set; }
        public int OhioID { get; set; }
    };
}

CFIProject/CFIProject/Controllers/HomeController.cs
using CFIProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CFIProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult Contact()
        {
            return View();
        }
        public IActionResult Keyfacts()
        {
            return View();
        }
    }
}

CFIProject/CFIProject/Controllers/NationalController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CFIProject.Models;
namespace CFIProject.Controllers
{
    public class NationalController : Controller
    {
        private readonly INationalRepo repo;

        public NationalController(INationalRepo repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            var national = repo.GetAllNational();

            return View(national);
        }

        public IActionResult UpdateNational(int id)
        {
            var national = repo.GetNational(id);

            repo.UpdateNational(national);

            if (national == null)
            {
                return View("NationalNotFound");
            }
            return View(national);
        }
       


    }
}

CFIProject/CFIProject/Controllers/OhioController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CFIProject.Models;

namespace CFIProject.Controllers
{
    public class OhioController : Controller
    {

        private readonly IOhioRepo repo;

        public OhioController(IOhioRepo repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            var ohio = repo.GetAllOhio();

            return View(ohio);
        }
        public IActionResult UpdateAllOhio(OhioModels ohio)
        {
            repo.UpdateAllOhio(ohio);

            return RedirectToAction("ViewOhio", new { ohio_ID = ohio.ohio_ID });
        }

        public IActionResult ViewOhio(int id)
        {
            var ohio = repo.GetAllOhio(id);

            return View(ohio);
        }
        public IActionResult UpdateProductToDatabase(OhioModels ohio)
        {
            repo.UpdateAllOhio( ohio);

            return RedirectToAction("ViewOhio", new { id = ohio.ohio_ID });
        }
        public IActionResult UpdateProductModel(int id)
        {
            OhioModels ohio = repo.GetAllOhio(id);
            repo.UpdateAllOhio(ohio);

            if (ohio == null)
            {
                return View("OhioNotFound");
            }
            return View(ohio);


        }
        


















    }

}

CFIProject/CFIProject/Views/Home/About.cshtml
 @{ViewData["Title"] = "About";
}
<h1>@ViewData["Title"]</h1>


<body style="background-color:beige">

    <br />
    <br />
    <br />
    <h1 class="text-center d-md-inline-block" id="ap">
        I began my journey in May 2019, it not only hit my self being,it hit me hard finacially as well.
        I put together this list of places that I found help, and then added some places you can
        research to see if they can help you.My wish is that this list can grow with contributions
        from warriors in every state, past and present, and find someone in need.There is enough to worry
        about on this journey,finances not being one of them.I wish you strength and you are not alone.
    </h1>
    <div class="text-center embed-responsive embed-responsive-4by3">
        <video controls="controls" autoplay="autoplay">
            <source src="~/videos/hospital.mp4" type="Video/mp4" />
            Your browser does not support the video tag.
        </video>
    </div>
                
              
    <footer><h3> Just one add could help someone in financial distress find hope</h3></footer>
    <h2 class="text-center">Will you be the light in the darkness for someone in need.Thanks be safe out there.</h2>
</body>

CFIProject/CFIProject/Views/Home/Contact.cshtml
@page 
<html>
    <body style="background-color:antiquewhite">



        <h2>HTML Forms</h2>

        <form id="Form1" action="/action_page.php">
            <label for="Name"> Name:</label><br>
            <input type="text" id="name" name="Name" value="Name"><br>
            <label for="email">Email:</label><br>
            <input type="text" id="Email" name="email" value="Email"><br><br>
            <label for="Concern">Concern</label><br/>
            <input type="Text" id="concern"name="Concern" value="Text" />

            <input type="submit" value="Submit">
       
        </form>
        <h2> Thank you for your feedback , Have a wonderful Day!!!</h2>
    </body>
</html>

CFIProject/CFIProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<link href="~/css/style.css" rel="stylesheet" />
<meta charset="utf-8">

<script src="jquery-3.2.0 min.js"></script>


<div class="fullscreen-bg">
    <video loop muted autoplay poster="img/videoframe.jpg" class="fullscreen-bg__video">
        <source src="~/videos/purple.mp4" type="video/webm">
        <source src="~/videos/purple.mp4" type="video/mp4">
        <source src="~/videos/purple.mp4 " type="video/ogg">
    </video>
</div>

CFIProject/CFIProject/Views/Home/KeyFacts.cshtml
<DOCTYPE>
    <html>
    <body style="background-color:antiquewhite">

        <h1 class="text-center">Some Key Facts Of Cancer</h1>
        <section>
            <IMG BORDER="0" ALIGN="Left" SRC="~/videos/armswide.jpg"><ul>
                <li>Cancers figure among the leading causes of death worldwide, accounting for 9.6 million deaths in 2018.</li>
                <li>Lung, colorectal, stomach, liver and breast cancers cause the most cancer deaths each year.</li>
                <li>The most frequent types of cancer differ between men and women.</li>
                <li>About one-third of cancer deaths are due to the five leading behavioral and dietary risks: high body mass index, low fruit <br />and vegetable intake, physical inactivity, tobacco use, alcohol use and are therefore preventable.</li>
            </ul>
        </section>
        <section>
               <ul>
                <li>Tobacco use is the most important risk factor for cancer causing over 20% of global cancer deaths.</li>
                <li>Cancer causing infections such as HBV/HCV and HPV are responsible for up to 25% of cancer cases in low- and middle-income countries.</li>
                <li>Cancer arises from the rapid creation of abnormal cells that grow beyond their usual boundaries. The change may be started by external agents and inherited genetic factors.</li>
                <li>More than 60% of world’s total new annual cases occur in Africa, Asia and Central and South America. These regions account for 70% of the world’s cancer deaths.</li>
              </ul>

            <IMG BORDER="0" ALIGN="Right" SRC="~/videos/hope.jpeg">
        </section>
        <section>


            <IMG BORDER="0" ALIGN="Left" SRC="~/videos/just.jpg"><ul>
                <li>

                    Cancer is the second leading cause of death globally, and is responsible for an estimated 9.6 million deaths in 2018. Globally, about 1 in 6 deaths is due to cancer.
                    Approximately 70% of deaths from cancer occur in low- and middle-income countries.
                    Around one third of deaths from cancer are due to the 5 leading behavioral and dietary risks: high body mass index, low fruit and vegetable intake, lack of physical activity, tobacco use, and alcohol use.
                    Tobacco use is the most important risk factor for cancer and is responsible for approximately 22% of cancer deaths (2).
                    Cancer causing infections, such as hepatitis and human papilloma virus (HPV), are responsible for up to 25% of cancer cases in low- and middle-income countries (3).
                    Late-stage presentation and inaccessible diagnosis and treatment are common. In 2017, only 26% of low-income countries reported having pathology services generally available in the public sector. More than 90% of high-income countries reported treatment services are available compared to less than 30% of low-income countries.
                    The economic impact of cancer is significant and is increasing. The total annual economic cost of cancer in 2010 was estimated at approximately US$ 1.16 trillion (4).
                    Only 1 in 5 low- and middle-income countries have the necessary data to drive cancer policy (5).
                    Cancer is a generic term for a large group of diseases that can affect any part of the body. Other terms used are malignant tumours and neoplasms. One defining feature of cancer is the rapid creation of abnormal cells that grow beyond their usual boundaries, and which can then invade adjoining parts of the body and spread to other organs, the latter process is referred to as metastasizing. Metastases are a major cause of death from cancer.
                    The problem
                    Cancer is a leading cause of death worldwide, accounting for an estimated 9.6 million deaths in 2018. The most common cancers are:
                </li>

            </ul>
        </section>
        <section>
            <IMG BORDER="0" ALIGN="right" SRC="~/videos/what.jpeg">





            <ul class="align-content-center">
                <li>
                    Lung (2.09 million cases)
                </li>
                <li>
                    Breast (2.09 million cases)
                </li>

                <li>Colorectal (1.80 million cases)</li>
                <li>Prostate (1.28 million cases)</li>
                <li>Skin cancer (non-melanoma) (1.04 million cases)</li>
                <li>Stomach (1.03 million cases)</li>
                <li>Lung (1.76 million deaths)</li>
                <li>Colorectal (862 000 deaths)</li>
                <li>Stomach (783 000 deaths)</li>
                <li>Liver (782 000 deaths)</li>
                <li>Breast (627 000 deaths)</li>
                <li>physical carcinogens, such as ultraviolet and ionizing radiation;</li>
                <li>chemical carcinogens, such as asbestos, components of tobacco smoke, aflatoxin (a food contaminant), and arsenic (a drinking water contaminant</li>
                <li>biological carcinogens, such as infections from certain viruses, bacteria, or parasites.</li>

             </ul>

        </section>


    </body>
</html>
</DOCTYPE>                    

CFIProject/CFIProject/Views/Home/myForm.cshtml
@model National

    <section id="main-content">
        <section id="wrapper"
            <div class ="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            <div class="col-md-4 col-md-offset-4">
                                <h1>CFI Contact Form </h1>
                            </div>
                        </header>


                    <div id="form"
                   <div class="panel-body">
                       <div class="row">
                           <div class="col-md-4 col-md-offset-1">
                               <div class="form-group">
                                   <asp:Label Text="Your Name" runat="server" />
                                   <asp:TextBox runat="server" Enabled="true" CssClass="form-control input-sm" placeholder="Your Name" />
                                   <br/>
                                   <br />
                                    <asp:Label Text="Your Email" runat="server" />
                                   <asp:Email runat="server" Enabled="true" CssClass="form-control input-sm" placeholder="Your Email" />
                                   <br />
                                   <br />
                                   <asp:Label Text="Your Concern" runat="server" />
                                   <asp:Textbox Rows="5" Columns="30" TextMode="MultiLine" runat="server" Enabled="true" CssClass="form-control input-sm-lg col-lg* "  placeholder="Your Concern" />
                                   <br />
                                   <br />
                                   <asp:Label Text="World Home" runat="server" />
                                   <asp:DropDownList runat="server" CssClass="form-control input-sm">
                                       <asp:ListItem Text="North America" />
                                       <asp:ListItem Text="Europe" />
                                       <asp:ListItem Text="Asia" />
                                       <asp:ListItem Text="Middle East" />
                                       <asp:ListItem Text="Australia" />
                                       <asp:ListItem Text="Africa" />
                                       <asp:ListItem Text="South America" />
                                       <asp:ListItem Text="Western Europe" />

                                   </asp:DropDownList>

                                    <input type="submit" class="btn btn-dark" value="Submit Button" />
                               </div>

                   </div>
                  </div>

              <p class="col-md-2 col-md-offset-1">Thank You for contacting us, have a great day!</p>

CFIProject/CFIProject/Views/National/ViewNational.cshtml
@model National

<h3>@Model.Name information </h3>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Address</th>
        <th>Website</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Assistance</th>
    </tr>

    <tr>
        <td>@Model.ID</td>
        <td>@Model.Name</td>
        <td>@Model.Address</td>
        <td>@Model.Website</td>
        <td>@Model.Phone</td>
        <td>@Model.Email</td>
        <td>@Model.Assistance</td>
    </tr>
</table>

CFIProject/CFIProject/Views/National/index.cshtml
@model IEnumerable<National>

<h1>National Resources </h1>
<br />
<table class="table table-striped">

    <tr>

        <th>ID</th>
        <th>Name</th>
        <th>Address</th>
        <th>Website</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Assistance</th>
    </tr>

    @foreach (var national in Model)
    {
        <tr>
            <td><a href=/National/ViewNational/@national.ID>@national.ID</a></td>
            <td>@national.Name</td>
            <td>@national.Address</td>
            <td>@national.Website</td>
            <td>@national.Phone</td>
            <td>@national.Email</td>
            <td>@national.Assistance</td>

        </tr>
    }





</table>

CFIProject/CFIProject/Views/Ohio/ViewOhio.cshtml
@model OhioModels

<h3>@Model.ohio_Name information </h3>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Address</th>
        <th>Website</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Assistance</th>
    </tr>

    <tr>
        <td>@Model.ohio_ID</td>
        <td>@Model.ohio_Name</td>
        <td>@Model.ohio_Address</td>
        <td>@Model.ohio_Website</td>
        <td>@Model.ohio_Phone</td>
        <td>@Model.ohio_Email</td>
        <td>@Model.ohio_Assistance</td>
    </tr>
</table>

CFIProject/CFIProject/Views/Ohio/index.cshtml
@model IEnumerable<OhioModels>

<h1>Ohio Resources</h1>
<br/>
<table class="table table-striped ">
    <tr>

        <th>ID</th>
        <th>Name</th>
        <th>Address</th>
        <th>Website</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Assistance</th>
    </tr>

     @foreach (var ohio in Model)
     {
<tr>
    <td><a href=/Ohio/ViewOhio/@ohio.ohio_ID>@ohio.ohio_ID</a></td>
   
    <td>@ohio.ohio_Name</td>
    <td>@ohio.ohio_Address</td>
    <td>@ohio.ohio_Website</td>
    <td>@ohio.ohio_Phone</td>
    <td>@ohio.ohio_Email</td>
    <td>@ohio.ohio_Assistance</td>
</tr>
     }
    
</table>
    

    
        
        
           

        

CFIProject/CFIProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CFIProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

</head>
<body style="background-color:antiquewhite">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CFIProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home<i class="fas fa-home"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy<i class="fas fa-user-secret"></i></a>
                        </li>
                        <li class="nav-item" />
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About<i class="fas fa-eject"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="National" asp-action="index">National<i class="fas fa-flag-usa"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ohio" asp-action="index">Ohio<i class="fab fa-nutritionix"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact" onclick="C:\Users\Michael\Desktop\CFIProject\CFIProject\CFIProject\CFIProject\Views\Home\Contact.cshtml">Contact<i class="fas fa-address-book"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="KeyFacts" >Key Facts<i class="fa fa-key" aria-hidden="true"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CFIProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>